{pkgs, ...}: {
  home.packages = with pkgs; [
    gh
    waybar
    btop
    libreoffice
    nwg-look
    networkmanagerapplet
    nautilus
    eog
    brightnessctl
    libnotify
    qbittorrent
    zed-editor
    corefonts
    xdg-desktop-portal-gtk
    xdg-desktop-portal
    libsForQt5.qtstyleplugin-kvantum
    libsForQt5.qt5ct
    qt6Packages.qtstyleplugin-kvantum
    qt6Packages.qt6ct
    wayland-logout
    blueman
    pavucontrol
    inter
    hyprpaper
    lazydocker
    vesktop
    obsidian
    pinta
    papirus-icon-theme
    tokyonight-gtk-theme
    mpv
    fastfetch
    slurp
    hyprpicker
    foliate
    yt-dlp
    nur.repos.tnmt.brave-origin
    proton-vpn
  ];
}
