{pkgs, ...}: {
  home.packages = with pkgs; [
    wl-clipboard
    nur.repos.trev.helium
    tree-sitter
    lazygit
    bottom
    nerd-fonts.jetbrains-mono
    nodejs
    python3
    lazygit
    gh
    waybar
    btop
    libreoffice
    nwg-look
    networkmanagerapplet
    nautilus
    eog
    brightnessctl
    libnotify
    qbittorrent
    zed-editor
    corefonts
    xdg-desktop-portal-gtk
    xdg-desktop-portal
    libsForQt5.qtstyleplugin-kvantum
    libsForQt5.qt5ct
    qt6Packages.qtstyleplugin-kvantum
    qt6Packages.qt6ct
    wayland-logout
    blueman
    pavucontrol
    inter
    hyprpaper
    lazydocker
    vesktop
    obsidian
    pinta
  ];
}
