{pkgs, ...}: {
  home.packages = with pkgs; [
    gh
    btop
    libreoffice
    nwg-look
    networkmanagerapplet
    nautilus
    eog
    brightnessctl
    libnotify
    qbittorrent
    zed-editor
    corefonts
    xdg-desktop-portal-gtk
    xdg-desktop-portal
    wayland-logout
    blueman
    pavucontrol
    inter
    hyprpaper
    lazydocker
    vesktop
    obsidian
    pinta
    papirus-icon-theme
    tokyonight-gtk-theme
    mpv
    fastfetch
    slurp
    hyprpicker
    foliate
    yt-dlp
    proton-vpn
    hyprmoncfg
    jetbrains.webstorm
  ];
}
