-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Media4 Inc N2255 0000000000000",
  mode = "1920x1080@75.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:BOE 0x07B5",
  disabled = true,
})
